# ==============================================================================
# TMUX CONFIG SRE 2026 - Jorge Ochoa
# ==============================================================================

# 1. Ajustes Generales de Terminal y Color
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -g mouse on               # Permite usar el ratón para scroll y redimensionar
set -g history-limit 50000     # Aumenta el historial para no perder logs de Edwin
set -g base-index 1           # Las ventanas empiezan en 1 (más fácil de alcanzar)
setw -g pane-base-index 1
set -s escape-time 0          # Elimina el retraso al presionar la tecla Esc

# 2. Atajos de Teclado (Prefix)
unbind C-b
set-option -g prefix C-a       # Cambiamos el prefijo a Ctrl+A (estándar SRE)
bind-key C-a send-prefix

# División de paneles intuitiva con la ruta actual
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Recarga rápida de configuración
bind r source-file ~/.tmux.conf \; display "¡Configuración TMUX recargada!"

# 3. Estética SRE (Azul Partnertech / Naranja AWS)
set -g status-style bg=default
set -g status-left-length 40
set -g status-left "#[fg=blue,bold] #S #[fg=white]| "
set -g status-right "#[fg=yellow] ☁️  SRE-PROD #[fg=white]| #[fg=cyan]%H:%M "

# Diseño de la ventana activa
setw -g window-status-current-style fg=white,bold,bg=blue
setw -g window-status-current-format " #I:#W#F "

# Colores de los bordes de paneles
set -g pane-border-style fg=black
set -g pane-active-border-style fg=blue

# 4. Modo Copia Estilo Vi
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
