palette = "cyberpunk_sre"

format = """
[](dir_bg)\
$directory\
[](fg:dir_bg bg:python_bg)\
$python\
[](fg:python_bg bg:git_bg)\
$git_branch\
$git_status\
[](fg:git_bg bg:status_bg)\
$os\
[](fg:status_bg)\
$character"""

[directory]
style = "bg:dir_bg fg:white bold"
format = "[  $path ]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[os]
disabled = false
style = "bg:status_bg fg:white"
format = "[ $symbol ]($style)"

[python]
symbol = "🐍 "
style = "bg:python_bg fg:black bold"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:git_bg fg:white bold"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:git_bg fg:white"
format = '([\[$all_status$ahead_behind\]]($style))'

[character]
success_symbol = "[ ❯](bold #89b4fa)"
error_symbol = "[ ❯](bold #f38ba8)"

# --- PALETA CYBERPUNK SRE (Contraste Máximo) ---
[palettes.cyberpunk_sre]
dir_bg = '#89b4fa'     # Azul zafiro brillante (Directorio)
python_bg = '#fab387'  # Naranja melocotón (Python)
git_bg = '#45475a'     # Gris superficie (Git)
status_bg = '#313244'  # Gris oscuro (OS/Info)
